# Generated by Django 5.2.4 on 2025-09-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_user_api_key_user_api_secret_user_is_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('symbolid', models.IntegerField()),
                ('precision', models.IntegerField(blank=True, null=True)),
                ('minimum_qty', models.IntegerField(default=1)),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
    ]
