# Generated by Django 5.2.4 on 2025-09-29 11:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_highlowstratergy_orderdetails_position_tradedetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='NA', max_length=25)),
                ('side', models.CharField(default='NA', max_length=25)),
                ('unique', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.date.today)),
                ('status', models.CharField(default='NA', max_length=25)),
                ('entry', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('stoploss', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('leverage', models.IntegerField(default=0)),
                ('capital', models.IntegerField(default=0)),
                ('stratergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.highlowstratergy')),
            ],
        ),
    ]
