# Generated by Django 5.2.4 on 2025-09-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_signalmaster_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='NA', max_length=255)),
                ('symbol', models.CharField(default='NA', max_length=255)),
                ('side', models.CharField(default='NA', max_length=255)),
                ('leverage', models.IntegerField(default=0)),
                ('capital', models.IntegerField(default=0)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.highlowstratergy')),
            ],
        ),
    ]
