# Generated by Django 5.2.4 on 2025-10-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_alter_position_unique_alter_tradedetails_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalmaster',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
