# Generated by Django 5.2.4 on 2025-10-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_alter_signalmaster_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminposition',
            name='capital',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=13),
        ),
    ]
