# Generated by Django 5.2.4 on 2025-10-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0014_copysignal_capital_copysignal_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlowstratergy',
            name='risk',
            field=models.CharField(default='Low', max_length=25),
        ),
    ]
