# Generated by Django 5.2.4 on 2025-10-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0015_highlowstratergy_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlowstratergy',
            name='stratergy_description',
            field=models.CharField(default='NA', max_length=500),
        ),
    ]
