# Generated by Django 5.2.4 on 2025-10-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0016_alter_highlowstratergy_stratergy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlowstratergy',
            name='overallReturn',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
