# Generated by Django 5.2.4 on 2025-10-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0017_highlowstratergy_overallreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlowstratergy',
            name='stratergy_code',
            field=models.CharField(default='NA', max_length=55),
        ),
    ]
