# Generated by Django 5.2.4 on 2025-10-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0018_alter_highlowstratergy_stratergy_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=250)),
                ('description', models.TextField(default='NA')),
                ('link', models.CharField(default='NA', max_length=100)),
            ],
        ),
    ]
