# Generated by Django 5.2.4 on 2025-10-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0021_customer_failorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_failorder',
            old_name='symbol',
            new_name='strategy',
        ),
    ]
