# Generated by Django 5.2.4 on 2025-10-27 03:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0025_highlowstratergy_strategy_allow'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlowstratergy',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who are allowed to access this strategy', related_name='allowed_strategies', to=settings.AUTH_USER_MODEL),
        ),
    ]
