# Generated by Django 5.2.4 on 2025-11-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0026_highlowstratergy_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='broker',
            field=models.CharField(default='DeltaExchange', max_length=100),
        ),
    ]
