# Generated by Django 5.2.4 on 2025-12-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0034_user_coindcx_link_user_deltaexchange_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedetails',
            name='margin',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
