# Generated by Django 5.2.4 on 2025-12-08 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0038_tutorial_broker_tutorial_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='latencycheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(default='NA', max_length=45)),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.IntegerField(default=0)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.highlowstratergy')),
            ],
        ),
    ]
