# Generated by Django 5.2.4 on 2025-12-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0039_latencycheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latencycheck',
            name='time_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='latencycheck',
            name='time_start',
            field=models.DateTimeField(),
        ),
    ]
