# Generated by Django 5.2.4 on 2025-12-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0040_alter_latencycheck_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokermodels',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
