# Generated by Django 5.2.4 on 2025-12-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0041_brokermodels_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokermodels',
            name='coindcx_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
