# Generated by Django 5.2.4 on 2025-12-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0046_user_is_business_report_user_is_credit_ai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copysignal',
            name='is_trailing',
            field=models.BooleanField(default=False),
        ),
    ]
