# Generated by Django 5.2.4 on 2025-09-29 10:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='highLowstratergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='TRADEARTH', max_length=25)),
                ('stratergy_code', models.CharField(default='NA', max_length=25)),
                ('name', models.CharField(default='NA', max_length=25)),
                ('full_name', models.CharField(default='NA', max_length=25)),
                ('stratergy_description', models.CharField(default='NA', max_length=25)),
                ('tag', models.JSONField(blank=True, null=True)),
                ('captial_requirement', models.TextField(default='NA')),
                ('entry_time', models.TextField(default='NA')),
                ('exit_time', models.TextField(default='NA')),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('target', models.TextField(default='NA')),
                ('sl', models.TextField(default='NA')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='NA', max_length=35)),
                ('stratergy', models.CharField(default='NA', max_length=15)),
                ('buyprice', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('sellprice', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('buyquantity', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('sellquantity', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('side', models.CharField(default='NA', max_length=15)),
                ('orderid', models.CharField(default='NA', max_length=15)),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('status', models.CharField(default='NA', max_length=15)),
                ('profit', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='NA', max_length=255)),
                ('symbol', models.CharField(default='NA', max_length=255)),
                ('side', models.CharField(default='NA', max_length=255)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('quantity', models.DecimalField(decimal_places=7, default=0, max_digits=13)),
                ('unique', models.IntegerField(default=0)),
                ('leverage', models.IntegerField(default=0)),
                ('stratergy', models.CharField(default='NA', max_length=15)),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tradeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='NA', max_length=35)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('side', models.CharField(default='NA', max_length=15)),
                ('unique', models.CharField(default='NA', max_length=35)),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('status', models.CharField(default='NA', max_length=15)),
                ('orderid', models.CharField(default='NA', max_length=35)),
                ('stratergy', models.CharField(default='NA', max_length=15)),
                ('remark', models.CharField(default='NA', max_length=85)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userStratergyPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy', to=settings.AUTH_USER_MODEL)),
                ('stratergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.highlowstratergy')),
            ],
        ),
    ]
