# Generated by Django 5.2.4 on 2025-10-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_adminposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='unique',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='tradedetails',
            name='unique',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
