# Generated by Django 5.2.4 on 2025-10-14 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0012_alter_adminposition_capital'),
    ]

    operations = [
        migrations.CreateModel(
            name='copysignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='NA', max_length=25)),
                ('symbolid', models.IntegerField(default=0)),
                ('side', models.CharField(default='NA', max_length=15)),
                ('target', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('stoploss', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('entry', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('typeq', models.CharField(default='NA', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(default='NA', max_length=105)),
                ('status', models.CharField(default='NA', max_length=45)),
                ('trailingpoints', models.IntegerField(default=0)),
                ('trailingprice', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copysignal', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.highlowstratergy')),
            ],
        ),
    ]
