# Generated by Django 5.2.4 on 2025-10-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0019_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='stratergy_name',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AddField(
            model_name='tradedetails',
            name='stratergy_name',
            field=models.CharField(default='NA', max_length=25),
        ),
    ]
