# Generated by Django 5.2.4 on 2025-10-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0022_rename_symbol_customer_failorder_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='stratergy_name',
            field=models.CharField(default='NA', max_length=25),
        ),
    ]
