# Generated by Django 5.2.4 on 2025-12-05 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0036_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_order', to='authenticate.brokermodels'),
        ),
        migrations.AddField(
            model_name='position',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_position', to='authenticate.brokermodels'),
        ),
        migrations.AddField(
            model_name='tradedetails',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_trade', to='authenticate.brokermodels'),
        ),
    ]
