# Generated by Django 5.2.4 on 2025-12-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0037_orderdetails_broker_position_broker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='broker',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tag',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
