# Generated by Django 5.2.4 on 2025-12-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0042_brokermodels_coindcx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokermodels',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
