# Generated by Django 5.2.4 on 2025-12-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0043_brokermodels_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='latencycheck',
            name='side',
            field=models.CharField(default='NA', max_length=45),
        ),
        migrations.AddField(
            model_name='latencycheck',
            name='type',
            field=models.CharField(default='NA', max_length=45),
        ),
        migrations.AddField(
            model_name='latencycheck',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
    ]
