# Generated by Django 5.2.4 on 2025-12-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0044_latencycheck_side_latencycheck_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlowstratergy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
