# Generated by Django 5.2.4 on 2025-12-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0045_alter_highlowstratergy_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_business_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_credit_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_learning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_orderlatency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_userstrategy',
            field=models.BooleanField(default=False),
        ),
    ]
