"""
Django settings for delta_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jh_=)j_%vhq&jguw$__g4xrrrh(51wv2*d5ulb!k!s$j@%jk(e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
AUTH_USER_MODEL = 'authenticate.User'

# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
    'rest_framework',
    "django_celery_beat",
    'corsheaders',
    'authenticate',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'delta_backend.urls'

CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = ('http://127.0.0.1:8000','http://localhost:3000','http://localhost:3001', 'http://192.168.1.33')


CORS_ALLOW_CREDENTIALS = True  # If using cookies or authentication
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
CORS_ALLOW_HEADERS = ["*"]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'delta_backend.wsgi.application'
ASGI_APPLICATION = 'delta_backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Use the MySQL backend
        'NAME': 'tradearth_db',                   # Name of the database
        'USER': 'tradearth',                       # MySQL username
        'PASSWORD': 'TradeEarth123!',             # MySQL password
        'HOST': '139.59.78.109',  # Your MySQL host
        'PORT': '3306',                       # Your MySQL port (default for DigitalOcean)
        
        'CONN_MAX_AGE': 60,
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "address": "redis://:Tradearth456s@139.59.78.109:6379/1",  # Use different DB than cache
                    "timeout": 30,  # Connection timeout in seconds
                    
                }
            ],
            "prefix": "asgi:",  # Key prefix
            "group_expiry": 86400,  # Group expiry in seconds (1 day)
            "capacity": 1000,  # Default channel capacity
            "channel_capacity": {
                "specific.channel.name": 2000,  # Custom capacity per channel
            },
            # "symmetric_encryption_keys": [b"your_encryption_key"],  # For message security
        },
    },
}

CHANNELS_REDIS_POOL_KWARGS = {
    "max_connections": 200,
    "timeout": 20,
    "retry_on_timeout": True,
    "health_check_interval": 30,
}


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://139.59.78.109:6379/0",  # Use 0 if you want default DB
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": "Tradearth456s",  # If you set a password
            "SOCKET_CONNECT_TIMEOUT": 5,  # seconds
            "SOCKET_TIMEOUT": 5,  # seconds
            "IGNORE_EXCEPTIONS": True,  # Prevents cache failures from crashing app
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 100,  # Adjust based on your needs
                "retry_on_timeout": True
            },
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
        },
        "KEY_PREFIX": "tradearth"  # Namespace your keys
    }
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

SECURE_PROXY_SSL_HEADER=('HTTP_X_FORWARDED_PROTO','https')
from datetime import datetime, timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1440),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
}

REST_FRAMEWORK = {
    "NON_FIELD_ERRORS_KEY": 'error',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'delta_backend.middleware.auth.CachedJWTAuthentication',
    ]
}
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_HOST = 'smtp.hostinger.com'
EMAIL_PORT = 587

EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_HOST_USER = "contact@tradearth.in"
#EMAIL_HOST_PASSWORD = "kyrjtemjjfciqpwi"
EMAIL_HOST_PASSWORD = "pcjiqwboongqlkcf"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
