-- Migration: 001_init.sql
-- Description: Initial database schema for AI Strategy Builder
-- Created: Initial schema setup
-- Notes:
--   - All timestamps stored in UTC
--   - Users table is a local snapshot of auth backend
--   - Auth backend is the source of truth for user data

-- Create users table (local snapshot of auth backend)
CREATE TABLE IF NOT EXISTS `users` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `external_user_id` INT NOT NULL UNIQUE COMMENT 'User ID from auth backend',
    `source` VARCHAR(50) NOT NULL DEFAULT 'auth_backend',
    `email` VARCHAR(255) NULL,
    `phone` VARCHAR(20) NULL,
    `username` VARCHAR(100) NULL,
    `first_name` VARCHAR(100) NULL,
    `last_name` VARCHAR(100) NULL,
    `broker` VARCHAR(50) NULL,
    `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
    `is_vendor` BOOLEAN NOT NULL DEFAULT FALSE,
    `timezone` VARCHAR(50) NOT NULL DEFAULT 'Asia/Kolkata',
    `country` VARCHAR(100) NOT NULL DEFAULT 'India',
    `raw_user_json` JSON NULL COMMENT 'Full user data snapshot from auth backend',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC timestamp',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'UTC timestamp',
    
    INDEX `idx_external_user_id` (`external_user_id`),
    INDEX `idx_email` (`email`),
    INDEX `idx_phone` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Local snapshot of user data from auth backend. Auth backend is source of truth.';

-- Create strategies table
CREATE TABLE IF NOT EXISTS `strategies` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL COMMENT 'Foreign key to users.id',
    `symbol` VARCHAR(20) NULL,
    `timeframe` VARCHAR(20) NULL,
    `strategy_json` JSON NOT NULL COMMENT 'Full strategy JSON object',
    `is_temp` BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'True for TEMP strategies, False for saved',
    `status` VARCHAR(50) NOT NULL DEFAULT 'draft' COMMENT 'draft, active, archived',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC timestamp',
    
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_is_temp` (`is_temp`),
    INDEX `idx_status` (`status`),
    
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Trading strategies generated by AI Strategy Builder.';

-- Create backtests table
CREATE TABLE IF NOT EXISTS `backtests` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `strategy_id` INT NOT NULL COMMENT 'Foreign key to strategies.id',
    `result_json` JSON NOT NULL COMMENT 'Full backtest result JSON',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC timestamp',
    
    INDEX `idx_strategy_id` (`strategy_id`),
    INDEX `idx_created_at` (`created_at`),
    
    FOREIGN KEY (`strategy_id`) REFERENCES `strategies`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Backtest results for strategies.';
