# Generated by Django 5.2.4 on 2025-09-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_symbolmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolmaster',
            name='contract_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
