# Generated by Django 5.2.4 on 2025-09-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_signalmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalmaster',
            name='type',
            field=models.CharField(default='NA', max_length=25),
        ),
    ]
