# Generated by Django 5.2.4 on 2025-10-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_copysignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='copysignal',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='copysignal',
            name='leverage',
            field=models.IntegerField(default=0),
        ),
    ]
