# Generated by Django 5.2.4 on 2025-10-15 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0020_orderdetails_stratergy_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_failorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(default='NA', max_length=35)),
                ('symbol', models.CharField(default='NA', max_length=35)),
                ('remarks', models.CharField(default='NA', max_length=105)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
