# Generated by Django 5.2.4 on 2025-10-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0023_position_stratergy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlowstratergy',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
