# Generated by Django 5.2.4 on 2025-10-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0024_highlowstratergy_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlowstratergy',
            name='strategy_allow',
            field=models.CharField(default='All', max_length=25),
        ),
    ]
