# Generated by Django 5.2.4 on 2025-12-04 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0028_user_refercode_brokermodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstratergyportfolio',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_strategies', to='authenticate.brokermodels'),
        ),
    ]
