# Generated by Django 5.2.4 on 2025-12-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0032_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlowstratergy',
            name='symbol',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='highlowstratergy',
            name='trading_type',
            field=models.CharField(default='Automatic', max_length=25),
        ),
    ]
