# Generated by Django 5.2.4 on 2025-12-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0033_highlowstratergy_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coindcx_link',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='user',
            name='deltaexchange_link',
            field=models.TextField(default='NA'),
        ),
    ]
